export default [
  {
    name: "Nona Galloway",
    email: "nonagalloway@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Mar 09, 2021, 11:02AM",
    avatar: "https://randomuser.me/api/portraits/med/women/42.jpg",
  },
  {
    name: "Katina Lewis",
    email: "katinalewis@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "May 02, 2023, 07:59PM",
    avatar: "https://randomuser.me/api/portraits/med/women/0.jpg",
  },
  {
    name: "Renee Gaines",
    email: "reneegaines@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "Nov 10, 2022, 08:13AM",
    avatar: "https://randomuser.me/api/portraits/med/men/34.jpg",
  },
  {
    name: "Misty Maldonado",
    email: "mistymaldonado@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Jan 05, 2022, 10:54AM",
    avatar: "https://randomuser.me/api/portraits/med/men/2.jpg",
  },
  {
    name: "Ericka Armstrong",
    email: "erickaarmstrong@cosmetex.com",
    status: "Active",
    role: "Admin",
    lastlogin: "Jul 09, 2022, 09:22AM",
    avatar: "https://randomuser.me/api/portraits/med/men/84.jpg",
  },
  {
    name: "Teri Hardy",
    email: "terihardy@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "Apr 20, 2022, 11:17PM",
    avatar: "https://randomuser.me/api/portraits/med/women/29.jpg",
  },
  {
    name: "Sarah Rasmussen",
    email: "sarahrasmussen@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Jul 17, 2022, 07:53PM",
    avatar: "https://randomuser.me/api/portraits/med/men/24.jpg",
  },
  {
    name: "Eugenia Rose",
    email: "eugeniarose@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Feb 22, 2022, 12:24AM",
    avatar: "https://randomuser.me/api/portraits/med/women/31.jpg",
  },
  {
    name: "Vera Thompson",
    email: "verathompson@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Sep 16, 2021, 06:46AM",
    avatar: "https://randomuser.me/api/portraits/med/men/91.jpg",
  },
  {
    name: "Elvira Hopper",
    email: "elvirahopper@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Sep 24, 2022, 01:32PM",
    avatar: "https://randomuser.me/api/portraits/med/women/12.jpg",
  },
  {
    name: "Deana Cruz",
    email: "deanacruz@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "Sep 23, 2022, 09:05AM",
    avatar: "https://randomuser.me/api/portraits/med/women/35.jpg",
  },
  {
    name: "Glass Ellis",
    email: "glassellis@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "May 09, 2023, 12:19PM",
    avatar: "https://randomuser.me/api/portraits/med/women/24.jpg",
  },
  {
    name: "Bettye Mcmillan",
    email: "bettyemcmillan@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Mar 14, 2023, 09:51PM",
    avatar: "https://randomuser.me/api/portraits/med/men/9.jpg",
  },
  {
    name: "Sanchez Mccray",
    email: "sanchezmccray@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Nov 17, 2021, 06:20PM",
    avatar: "https://randomuser.me/api/portraits/med/men/35.jpg",
  },
  {
    name: "Patricia Mosley",
    email: "patriciamosley@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Mar 25, 2022, 01:10PM",
    avatar: "https://randomuser.me/api/portraits/med/women/40.jpg",
  },
  {
    name: "Manning Russo",
    email: "manningrusso@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Jul 13, 2021, 09:41PM",
    avatar: "https://randomuser.me/api/portraits/med/men/47.jpg",
  },
  {
    name: "Terrie Gentry",
    email: "terriegentry@cosmetex.com",
    status: "Active",
    role: "Admin",
    lastlogin: "May 10, 2022, 05:24AM",
    avatar: "https://randomuser.me/api/portraits/med/men/61.jpg",
  },
  {
    name: "Charity Cantu",
    email: "charitycantu@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Dec 11, 2021, 10:10AM",
    avatar: "https://randomuser.me/api/portraits/med/men/68.jpg",
  },
  {
    name: "Ashley Finch",
    email: "ashleyfinch@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "May 04, 2023, 04:41AM",
    avatar: "https://randomuser.me/api/portraits/med/women/24.jpg",
  },
  {
    name: "Bobbie Arnold",
    email: "bobbiearnold@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Jul 13, 2021, 07:53PM",
    avatar: "https://randomuser.me/api/portraits/med/men/55.jpg",
  },
  {
    name: "Josefina Mayer",
    email: "josefinamayer@cosmetex.com",
    status: "Invited",
    role: "Sales Rep",
    lastlogin: "Mar 19, 2023, 03:51PM",
    avatar: "https://randomuser.me/api/portraits/med/men/96.jpg",
  },
  {
    name: "Hinton Hood",
    email: "hintonhood@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Jun 04, 2021, 02:04AM",
    avatar: "https://randomuser.me/api/portraits/med/men/98.jpg",
  },
  {
    name: "Duffy Hebert",
    email: "duffyhebert@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Jan 26, 2021, 08:01AM",
    avatar: "https://randomuser.me/api/portraits/med/women/70.jpg",
  },
  {
    name: "Juliana Foreman",
    email: "julianaforeman@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "Jan 31, 2022, 04:48AM",
    avatar: "https://randomuser.me/api/portraits/med/women/76.jpg",
  },
  {
    name: "Cathy Johnston",
    email: "cathyjohnston@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Dec 08, 2021, 08:00PM",
    avatar: "https://randomuser.me/api/portraits/med/women/6.jpg",
  },
  {
    name: "Lamb Joyner",
    email: "lambjoyner@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Dec 08, 2022, 10:15PM",
    avatar: "https://randomuser.me/api/portraits/med/men/74.jpg",
  },
  {
    name: "Dawn Evans",
    email: "dawnevans@cosmetex.com",
    status: "Invited",
    role: "Sales Rep",
    lastlogin: "Jul 20, 2021, 03:54PM",
    avatar: "https://randomuser.me/api/portraits/med/women/26.jpg",
  },
  {
    name: "Alvarado Bradshaw",
    email: "alvaradobradshaw@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Jun 16, 2022, 01:53PM",
    avatar: "https://randomuser.me/api/portraits/med/men/51.jpg",
  },
  {
    name: "Jensen Sampson",
    email: "jensensampson@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Feb 09, 2023, 03:04PM",
    avatar: "https://randomuser.me/api/portraits/med/men/2.jpg",
  },
  {
    name: "Janice Foley",
    email: "janicefoley@cosmetex.com",
    status: "Active",
    role: "Admin",
    lastlogin: "Feb 08, 2021, 02:10AM",
    avatar: "https://randomuser.me/api/portraits/med/women/37.jpg",
  },
  {
    name: "Ines Shelton",
    email: "inesshelton@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Jun 10, 2021, 11:02AM",
    avatar: "https://randomuser.me/api/portraits/med/men/44.jpg",
  },
  {
    name: "Reed Porter",
    email: "reedporter@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Nov 12, 2021, 12:23AM",
    avatar: "https://randomuser.me/api/portraits/med/men/36.jpg",
  },
  {
    name: "Jennifer Keller",
    email: "jenniferkeller@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Apr 01, 2022, 08:40AM",
    avatar: "https://randomuser.me/api/portraits/med/women/28.jpg",
  },
  {
    name: "Perkins Odonnell",
    email: "perkinsodonnell@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "Oct 09, 2022, 11:17PM",
    avatar: "https://randomuser.me/api/portraits/med/men/37.jpg",
  },
  {
    name: "William Day",
    email: "williamday@cosmetex.com",
    status: "Active",
    role: "Admin",
    lastlogin: "Feb 12, 2023, 01:14AM",
    avatar: "https://randomuser.me/api/portraits/med/women/85.jpg",
  },
  {
    name: "May Sanford",
    email: "maysanford@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Jun 08, 2022, 10:26PM",
    avatar: "https://randomuser.me/api/portraits/med/men/37.jpg",
  },
  {
    name: "Prince Blanchard",
    email: "princeblanchard@cosmetex.com",
    status: "Invited",
    role: "Sales Rep",
    lastlogin: "May 07, 2021, 12:56PM",
    avatar: "https://randomuser.me/api/portraits/med/men/87.jpg",
  },
  {
    name: "Rosales Sears",
    email: "rosalessears@cosmetex.com",
    status: "Invited",
    role: "Sales Leader",
    lastlogin: "Jul 24, 2022, 03:20AM",
    avatar: "https://randomuser.me/api/portraits/med/men/96.jpg",
  },
  {
    name: "Kathrine Boone",
    email: "kathrineboone@cosmetex.com",
    status: "Invited",
    role: "Sales Rep",
    lastlogin: "Jun 08, 2022, 12:16AM",
    avatar: "https://randomuser.me/api/portraits/med/women/77.jpg",
  },
  {
    name: "Mae Hendricks",
    email: "maehendricks@cosmetex.com",
    status: "Invited",
    role: "Sales Rep",
    lastlogin: "Jun 04, 2021, 05:28PM",
    avatar: "https://randomuser.me/api/portraits/med/women/14.jpg",
  },
  {
    name: "Nolan Page",
    email: "nolanpage@cosmetex.com",
    status: "Active",
    role: "Admin",
    lastlogin: "Jan 08, 2021, 08:01PM",
    avatar: "https://randomuser.me/api/portraits/med/women/1.jpg",
  },
  {
    name: "Wanda Frye",
    email: "wandafrye@cosmetex.com",
    status: "Active",
    role: "Sales Rep",
    lastlogin: "Mar 27, 2023, 03:48PM",
    avatar: "https://randomuser.me/api/portraits/med/men/52.jpg",
  },
  {
    name: "Kent Walls",
    email: "kentwalls@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Apr 05, 2022, 02:39AM",
    avatar: "https://randomuser.me/api/portraits/med/men/22.jpg",
  },
  {
    name: "Isabella Noble",
    email: "isabellanoble@cosmetex.com",
    status: "Invited",
    role: "Admin",
    lastlogin: "Mar 30, 2022, 04:32PM",
    avatar: "https://randomuser.me/api/portraits/med/men/53.jpg",
  },
  {
    name: "Bertha Ford",
    email: "berthaford@cosmetex.com",
    status: "Active",
    role: "Sales Leader",
    lastlogin: "Feb 16, 2021, 12:17AM",
    avatar: "https://randomuser.me/api/portraits/med/women/54.jpg",
  },
];
